"""de novo de novo

Revision ID: 02ed71a97129
Revises: 
Create Date: 2022-04-01 19:35:55.700583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ed71a97129'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('sigla', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_curso')),
    sa.UniqueConstraint('nome', name=op.f('uq_curso_nome')),
    sa.UniqueConstraint('sigla', name=op.f('uq_curso_sigla'))
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=1000), nullable=True),
    sa.Column('firstname', sa.String(length=30), nullable=True),
    sa.Column('lastname', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('matricula', sa.String(length=30), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('naonulanova', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('matricula', name=op.f('uq_user_matricula')),
    sa.UniqueConstraint('telefone', name=op.f('uq_user_telefone')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('amizade',
    sa.Column('primario', sa.Integer(), nullable=False),
    sa.Column('secundario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['primario'], ['user.id'], name=op.f('fk_amizade_primario_user')),
    sa.ForeignKeyConstraint(['secundario'], ['user.id'], name=op.f('fk_amizade_secundario_user')),
    sa.PrimaryKeyConstraint('primario', 'secundario', name=op.f('pk_amizade'))
    )
    op.create_table('cursos_alunos',
    sa.Column('aluno', sa.Integer(), nullable=False),
    sa.Column('curso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno'], ['user.id'], name=op.f('fk_cursos_alunos_aluno_user')),
    sa.ForeignKeyConstraint(['curso'], ['curso.id'], name=op.f('fk_cursos_alunos_curso_curso')),
    sa.PrimaryKeyConstraint('aluno', 'curso', name=op.f('pk_cursos_alunos'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cursos_alunos')
    op.drop_table('amizade')
    op.drop_table('user')
    op.drop_table('curso')
    # ### end Alembic commands ###
