"""nao nula

Revision ID: 34d9b7a76700
Revises: 56afa5f5d237
Create Date: 2022-03-28 17:08:18.835492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "34d9b7a76700"
down_revision = "56afa5f5d237"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "naonulanova",
                sa.String(length=30),
                nullable=False,
                server_default="blob blob",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("naonulanova")

    # ### end Alembic commands ###
