"""Novos atributos para Usuario

Revision ID: 56afa5f5d237
Revises: db3fa63860e3
Create Date: 2022-03-28 16:59:51.875961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56afa5f5d237'
down_revision = 'db3fa63860e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('lastname', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('matricula', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.String(length=30), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_matricula'), ['matricula'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_telefone'), ['telefone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_telefone'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_matricula'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.drop_column('telefone')
        batch_op.drop_column('matricula')
        batch_op.drop_column('email')
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=30), nullable=False),
    sa.Column('senha', sa.VARCHAR(length=100), nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('firstname', sa.VARCHAR(length=30), nullable=False),
    sa.Column('lastname', sa.VARCHAR(length=120), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('matricula', sa.VARCHAR(length=30), nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_user'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('matricula', name='uq_user_matricula'),
    sa.UniqueConstraint('telefone', name='uq_user_telefone'),
    sa.UniqueConstraint('username', name='uq_user_username')
    )
    # ### end Alembic commands ###
