"""teste

Revision ID: 8b626fbd7356
Revises: 02ed71a97129
Create Date: 2022-04-08 19:33:20.677345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b626fbd7356'
down_revision = '02ed71a97129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat'))
    )
    op.create_table('chat_users',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('chat', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat'], ['chat.id'], name=op.f('fk_chat_users_chat_chat')),
    sa.ForeignKeyConstraint(['user'], ['user.id'], name=op.f('fk_chat_users_user_user')),
    sa.PrimaryKeyConstraint('user', 'chat', name=op.f('pk_chat_users'))
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=200), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_message_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    op.create_table('menssagens_chat',
    sa.Column('chat', sa.Integer(), nullable=False),
    sa.Column('message', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chat'], ['chat.id'], name=op.f('fk_menssagens_chat_chat_chat')),
    sa.ForeignKeyConstraint(['message'], ['message.id'], name=op.f('fk_menssagens_chat_message_message')),
    sa.PrimaryKeyConstraint('chat', 'message', name=op.f('pk_menssagens_chat'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menssagens_chat')
    op.drop_table('message')
    op.drop_table('chat_users')
    op.drop_table('chat')
    # ### end Alembic commands ###
