"""usuarios tem amigos de novo

Revision ID: db3fa63860e3
Revises: 74d782406e61
Create Date: 2022-03-16 17:05:47.419923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db3fa63860e3'
down_revision = '74d782406e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amizade',
    sa.Column('primario', sa.Integer(), nullable=False),
    sa.Column('secundario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['primario'], ['user.id'], name=op.f('fk_amizade_primario_user')),
    sa.ForeignKeyConstraint(['secundario'], ['user.id'], name=op.f('fk_amizade_secundario_user')),
    sa.PrimaryKeyConstraint('primario', 'secundario', name=op.f('pk_amizade'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amizade')
    # ### end Alembic commands ###
